# numpy

In [ ]:
import numpy as np

In [ ]:
v1 = np.array([1,2,3,4])

In [ ]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [ ]:
v2 = np.arange(1,10,2) **3
print(v2)

[  1  27 125 343 729]


행렬

In [ ]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
v2 = v1.reshape(2,6)
v2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
v2 = v1.reshape(2,6, order='F ') 
v2

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [ ]:
v1 = np.arange(1,5)
v2 = v1.reshape(2,2)

In [ ]:
v3 = np.arange(1,5).reshape(2,2)
v3

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.add(v2,v2)) #행렬 계산

[[2 4]
 [6 8]]


In [ ]:
print(np.multiply(v2,v2))

[[ 1  4]
 [ 9 16]]


In [ ]:
print(np.dot(v2,v2))

[[ 7 10]
 [15 22]]


In [ ]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
v2 = v1.reshape(2,3,2) #3차원 데이터구조
v2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
v3 = np.arange(3.5,10.5,2, dtype = float) 

In [ ]:
print(v3)

[3.5 5.5 7.5 9.5]


In [ ]:
v4 = v3.reshape(2,2
              )

In [ ]:
v4

array([[3.5, 5.5],
       [7.5, 9.5]])

In [ ]:
print(np.amax(v4))

9.5


In [ ]:
print(v4.dtype)
print(v4.shape)

float64
(2, 2)
